name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Run Unit tests
      run: |
        go test -race ./...

    - name: Check it's own cyclomatic complexity
      run: go run ./cmd/cyclop/ ./pkg/analyzer/
